# For local development
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: t3_app
    environment:
      POSTGRES_USER: t3
      POSTGRES_PASSWORD: t3
      POSTGRES_DB: t3DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
